# Data
train_json: datasets/coco/train.json
val_json: datasets/coco/val.json
class_names: [person, bicycle, car, motorcycle, airplane, bus, train, truck, boat, traffic_light,
              fire_hydrant, stop_sign, parking_meter, bench, bird, cat, dog, horse, sheep, cow,
              elephant, bear, zebra, giraffe, backpack, umbrella, handbag, tie, suitcase, frisbee,
              skis, snowboard, sports_ball, kite, baseball_bat, baseball_glove, skateboard,
              surfboard, tennis_racket, bottle, wine_glass, cup, fork, knife, spoon, bowl, banana,
              apple, sandwich, orange, broccoli, carrot, hot_dog, pizza, donut, cake, chair, couch,
              potted_plant, bed, dining_table, toilet, tv, laptop, mouse, remote, keyboard,
              cell_phone, microwave, oven, toaster, sink, refrigerator, book, clock, vase, scissors,
              teddy_bear, hair_drier, toothbrush]
recall_steps: 101
image_mean: [123., 117., 104.]
image_stddev: [1., 1, 1.]

# Model
model: SSD
backbone:
  name: VGG16
  num_stages: 7
input_size: 512
anchor_scales: [0.04, 0.1, 0.26, 0.42, 0.58, 0.74, 0.9]
anchor_aspect_ratios: [[1, 2], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2], [1, 2]]

# Training
batch_size: 32
epochs: 130
optim:
  name: SGD
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005
scheduler:
  name: MultiStepLR
  milestones: [90, 110]
  gamma: 0.1